---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: nfs-server
    spec:
      nodeSelector: 
        kubernetes.io/hostname: node0
      containers:
      - name: nfs-server
        image: k8s.gcr.io/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /data1
            name: mypvc1
          - mountPath: /data2
            name: mypvc2
          - mountPath: /data3
            name: mypvc3
          - mountPath: /nginx
            name: nginx-volume
      volumes:
        - name: mypvc1
          hostPath:
            path: /data1
        - name: mypvc2
          hostPath:
            path: /data2
        - name: mypvc3
          hostPath:
            path: /data3
        - name: nginx-volume
          hostPath:
            path: /nginx
---
kind: Service
apiVersion: v1
metadata:
  name: nfs-server
spec:
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    name: nfs-server

