apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: use IP from nfs-server ClusterIP
    path: "/exports/nginx"
